# Generated by Django 2.2.12 on 2020-05-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloger',
            name='image',
            field=models.ImageField(blank=True, default='no photo', null=True, upload_to='static/img/examples/'),
        ),
    ]
